### ISSUE TITLE
[main/ERROR] [Sponge]: Could not pass FMLConstructionEvent to Plugin

### ISSUE THREAD

**Issue by Elias79** [Katrix-/HomeSweetHome#10]
MultiMC version: 0.6.1-1177

Minecraft folder is:
C:/- Spel -/Minecraft/MultiMC/instances/Sponge/.minecraft

Java path is:
C:/ProgramData/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_162, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/- Spel -/Minecraft/MultiMC/instances/Sponge/natives

Libraries:
  C:/- Spel -/Minecraft/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/mojang/realms/1.10.18/realms-1.10.18.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.1.2555/forge-1.12.2-14.23.1.2555-universal.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/jline/jline/2.13/jline-2.13.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/- Spel -/Minecraft/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/- Spel -/Minecraft/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  Akatlib-7-0-0-2.3.1-assembly
  homesweethome-7-0-0-2.2.0-assembly
  spongeforge-1.12.2-2555-7.0.0-BETA-2811

Params:
  --username  --version MultiMC5 --gameDir C:/- Spel -/Minecraft/MultiMC/instances/Sponge/.minecraft --assetsDir C:/- Spel -/Minecraft/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: max (if available)

Java Arguments:
[-XX:+UnlockExperimentalVMOptions, -XX:+UseG1GC, -XX:G1NewSizePercent=20, -XX:G1ReservePercent=20, -XX:MaxGCPauseMillis=50, -XX:G1HeapRegionSize=16M, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 12280

Using onesix launcher.

2018-02-07 09:01:00,710 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-02-07 09:01:00,714 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[09:01:00] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:01:00] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[09:01:00] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[09:01:00] [main/INFO] [FML]: Forge Mod Loader version 14.23.1.2555 for Minecraft 1.12.2 loading
[09:01:00] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_162, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_162
[09:01:01] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.12.2-2555-7.0.0-BETA-2811.jar
[09:01:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:01:01] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[09:01:01] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/C:/-%20Spel%20-/Minecraft/MultiMC/instances/Sponge/.minecraft/mods/spongeforge-1.12.2-2555-7.0.0-BETA-2811.jar Service=LaunchWrapper Env=CLIENT
[09:01:01] [main/WARN] [FML]: The coremod SpongeCoremod (org.spongepowered.mod.SpongeCoremod) is not signed!
[09:01:01] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[09:01:01] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[09:01:01] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[09:01:01] [main/INFO] [mixin]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[09:01:01] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:01:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:01:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[09:01:01] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
2018-02-07 09:01:02,468 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-02-07 09:01:02,481 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2018-02-07 09:01:02,481 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[09:01:03] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[09:01:03] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[09:01:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[09:01:03] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[09:01:03] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@511505e7
[09:01:03] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[09:01:04] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:01:04] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[09:01:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[09:01:04] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[09:01:09] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.client.main.Main}
[09:01:11] [main/INFO]: Setting user: <PROFILE NAME>
[09:01:17] [main/WARN]: Skipping bad option: lastServer:
[09:01:17] [main/INFO]: LWJGL Version: 2.9.4
[09:01:22] [main/INFO] [FML]: -- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 257071368 bytes (245 MB) / 536870912 bytes (512 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 9 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2555-7.0.0-BETA-2811.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1010' Renderer: 'AMD Radeon R9 200 Series'
[09:01:22] [main/INFO] [FML]: MinecraftForge v14.23.1.2555 Initialized
[09:01:22] [main/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[09:01:22] [main/INFO] [FML]: Replaced 1036 ore ingredients
[09:01:22] [main/INFO] [Sponge]: Found mcmod.info at jar:file:/C:/-%20Spel%20-/Minecraft/MultiMC/instances/Sponge/.minecraft/mods/spongeforge-1.12.2-2555-7.0.0-BETA-2811.jar!/mcmod.info
[09:01:22] [main/INFO] [Sponge]: Creating injector in stage 'PRODUCTION'
[09:01:24] [Thread-3/INFO] [FML]: Using sync timing. 200 frames of Display.update took 161544753 nanos
[09:01:24] [main/WARN] [Sponge]: Skipping org.spongepowered.api.world.BlockChangeFlags.NEIGHBOR_PHYSICS
[09:01:24] [main/WARN] [Sponge]: Skipping org.spongepowered.api.world.BlockChangeFlags.NEIGHBOR_PHYSICS
[09:01:26] [main/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[09:01:26] [main/INFO] [FML]: Searching C:\- Spel -\Minecraft\MultiMC\instances\Sponge\.minecraft\mods for mods
[09:01:27] [main/INFO] [FML]: Forge Mod Loader has identified 8 mods to load
[09:01:28] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, spongeapi, sponge, katlib, homesweethome] at CLIENT
[09:01:28] [main/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, spongeapi, sponge, katlib, homesweethome] at SERVER
[09:01:29] [main/WARN] [FML]: =============================================================
[09:01:29] [main/WARN] [FML]: MOD HAS DIRECT REFERENCE System.exit() THIS IS NOT ALLOWED REROUTING TO FML!
[09:01:29] [main/WARN] [FML]: Offender: io/github/katrix/katlib/shade/scala/sys/package$.exit(I)Lio/github/katrix/katlib/shade/scala/runtime/Nothing$;
[09:01:29] [main/WARN] [FML]: Use FMLCommonHandler.exitJava instead
[09:01:29] [main/WARN] [FML]: =============================================================
[09:01:29] [main/ERROR] [Sponge]: Could not pass FMLConstructionEvent to Plugin{id=homesweethome, name=HomeSweetHome, version=2.2.0-7.0.0, description=HomeSweetHome-7.0.0, authors=[Katrix], source=C:\- Spel -\Minecraft\MultiMC\instances\Sponge\.minecraft\mods\homesweethome-7-0-0-2.2.0-assembly.jar}
java.lang.AssertionError: assertion failed
	at io.github.katrix.katlib.shade.scala.Predef$.assert(Predef.scala:204) ~[Predef$.class:2.3.1]
	at io.github.katrix.homesweethome.HomeSweetHome$.<init>(HomeSweetHome.scala:53) ~[HomeSweetHome$.class:2.2.0]
	at io.github.katrix.homesweethome.HomeSweetHome$.<clinit>(HomeSweetHome.scala) ~[HomeSweetHome$.class:2.2.0]
	at io.github.katrix.homesweethome.HomeSweetHome.gameConstruct(HomeSweetHome.scala:111) ~[HomeSweetHome.class:2.2.0]
	at org.spongepowered.common.event.listener.GameConstructionEventListener_HomeSweetHome_gameConstruct4.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.0.0-BETA-2811]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2811]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2811]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:563) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[09:01:29] [main/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:SpongeForge, FMLFileResourcePack:KatLib, FMLFileResourcePack:HomeSweetHome
[09:01:29] [main/INFO] [FML]: Processing ObjectHolder annotations
[09:01:29] [main/INFO] [FML]: Found 1168 ObjectHolder annotations
[09:01:29] [main/INFO] [FML]: Identifying ItemStackHolder annotations
[09:01:29] [main/INFO] [FML]: Found 0 ItemStackHolder annotations
[09:01:29] [main/INFO] [FML]: Configured a dormant chunk cache size of 0
[09:01:30] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Starting version check at http://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[09:01:30] [Forge Version Check/INFO] [ForgeVersionCheck]: [forge] Found status: OUTDATED Target: 14.23.2.2611
[09:01:30] [main/INFO] [FML]: Applying holder lookups
[09:01:30] [main/INFO] [FML]: Holder lookups applied
[09:01:30] [main/INFO] [FML]: Applying holder lookups
[09:01:30] [main/INFO] [FML]: Holder lookups applied
[09:01:30] [main/INFO] [FML]: Applying holder lookups
[09:01:30] [main/INFO] [FML]: Holder lookups applied
[09:01:30] [main/INFO] [FML]: Applying holder lookups
[09:01:30] [main/INFO] [FML]: Holder lookups applied
[09:01:30] [main/INFO] [FML]: Injecting itemstacks
[09:01:30] [main/INFO] [FML]: Itemstack injection complete
[09:01:31] [Sound Library Loader/INFO]: Starting up SoundSystem...
[09:01:31] [Thread-6/INFO]: Initializing LWJGL OpenAL
[09:01:31] [Thread-6/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[09:01:31] [Thread-6/INFO]: OpenAL initialized.
[09:01:31] [Sound Library Loader/INFO]: Sound engine started
[09:01:33] [main/INFO] [FML]: Max texture size: 16384
[09:01:35] [main/INFO]: Created: 512x512 textures-atlas
[09:01:37] [main/INFO] [FML]: Applying holder lookups
[09:01:37] [main/INFO] [FML]: Holder lookups applied
[09:01:37] [main/INFO] [STDERR]: [org.spongepowered.common.registry.SpongeGameRegistry:throwRegistryEvent:610]: derp
[09:01:38] [main/WARN] [Sponge]: Plugin 'katlib' is attempting to register command 'KatLib' with an uppercase character - adjusting to 'katlib'
[09:01:38] [main/ERROR] [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=homesweethome, name=HomeSweetHome, version=2.2.0-7.0.0, description=HomeSweetHome-7.0.0, authors=[Katrix], source=C:\- Spel -\Minecraft\MultiMC\instances\Sponge\.minecraft\mods\homesweethome-7-0-0-2.2.0-assembly.jar}
java.lang.NoClassDefFoundError: Could not initialize class io.github.katrix.homesweethome.HomeSweetHome$
	at io.github.katrix.homesweethome.HomeSweetHome.init(HomeSweetHome.scala:116) ~[HomeSweetHome.class:2.2.0]
	at org.spongepowered.common.event.listener.GameInitializationEventListener_HomeSweetHome_init3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.0.0-BETA-2811]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:333) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2811]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2811]
	at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:232) [SpongeMod.class:1.12.2-2555-7.0.0-BETA-2811]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:561) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:719) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_162]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_162]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[09:01:38] [main/INFO] [FML]: Injecting itemstacks
[09:01:38] [main/INFO] [FML]: Itemstack injection complete
[09:01:38] [main/INFO] [FML]: Forge Mod Loader has successfully loaded 8 mods
[09:01:38] [main/WARN]: Skipping bad option: lastServer:
[09:01:38] [main/INFO]: Narrator library for x64 successfully loaded
[09:02:05] [main/INFO]: Stopping!
[09:02:05] [main/INFO]: SoundSystem shutting down...
[09:02:06] [main/WARN]: Author: Paul Lamb, www.paulscode.com
Process exited with code 0.
MultiMC: Log upload triggered at: 07 Feb 2018 09:02:13 +0100
MultiMC: Log uploaded to: https://paste.ee/p/vwPbs
Clipboard copy at: 07 Feb 2018 09:03:55 +0100

**Comment by Katrix** [comment]
Fixed in 2.2.1
